(require '[clojure.spec.alpha :as s])
(def string-collection? (s/coll-of string?))
(s/valid? string-collection? ["Hi" "Hello"])
(def number-or-string? (s/or :number number? :string string?))
(s/valid? number-or-string? 1)
(s/valid? number-or-string? "Hi")
(def number-or-string-collection? (s/coll-of number-or-string?))
(s/valid? number-or-string-collection? [1 "Hi" "India" 42])
(s/valid? number-or-string-collection? [1 "Hi" "India" 42 :keyword])
