(defrecord Car [name top-speed])
(def tata-nano (->Car "Tata Nano" 120))
(:name tata-nano)
(get tata-nano :name)
(:top-speed tata-nano)
(get tata-nano :top-speed)
(def ambassador (map->Car {:name "Ambassador", :top-speed 240}))
(:name ambassador)
(get ambassador :name)
(:top-speed ambassador)
(get ambassador :top-speed)