(def nums ["zero" "one" "two" "three" "four" "five" "six"])
(nth nums 5)
{"name" "Bashir" "age" 12}
(hash-map "name" "Bashir" "age" 20)
(def friend {"name" "Bashir" "age" 12})
(get friend "name")
(friend "name")
(type "name")
(type :name)
(def wise-friend {:name "Periyaar" :age 90})
(wise-friend :age)
(println (wise-friend :name) "is very wise.")
(:name wise-friend)
(assoc wise-friend :belief "Rationalism")
(wise-friend :belief)
(dissoc wise-friend :age)
(keys wise-friend)
(vals wise-friend)
(assoc wise-friend "name" "Ramasamy")